repos:
  - repo: https://github.com/ambv/black
    rev: '24.4.2'
    hooks:
      - id: black
        language_version: python3.12.2

  - repo: https://github.com/pycqa/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/necaris/pre-commit-pyright
    rev: '1.1.53'
    hooks:
      - id: pyright